#!/usr/bin/env python3
"""
AutoVAPT - Module 3: API Mapper
================================
Catalogs discovered API endpoints for a target application and produces
a simple Markdown inventory report. Endpoints are stored in a JSON file
so they can be incrementally built up during recon and reused by other
modules (e.g. feeding URLs into auth_checker.py).

Usage:
    python api_mapper.py --list
    python api_mapper.py --add /identity/api/auth/login --method POST --desc "Login endpoint" --auth no
    python api_mapper.py --report ../reports/api_inventory_report.md
"""

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_DB = Path(__file__).resolve().parent.parent / "findings" / "endpoints.json"


# --------------------------------------------------------------------------
# Storage
# --------------------------------------------------------------------------

def load_endpoints(db_path: Path) -> list:
    if not db_path.exists():
        return []
    with open(db_path) as fh:
        data = json.load(fh)

    # Support both the simple flat list-of-strings format and the richer
    # list-of-objects format -- normalize everything to objects in memory.
    normalized = []
    for entry in data:
        if isinstance(entry, str):
            normalized.append({"path": entry, "method": "UNKNOWN", "description": "", "auth_required": "unknown"})
        else:
            normalized.append(entry)
    return normalized


def save_endpoints(db_path: Path, endpoints: list):
    db_path.parent.mkdir(parents=True, exist_ok=True)
    with open(db_path, "w") as fh:
        json.dump(endpoints, fh, indent=2)


def add_endpoint(endpoints: list, path: str, method: str, description: str, auth_required: str) -> list:
    for e in endpoints:
        if e["path"] == path and e.get("method", "UNKNOWN") == method:
            e.update({
                "description": description or e.get("description", ""),
                "auth_required": auth_required or e.get("auth_required", "unknown"),
            })
            return endpoints
    endpoints.append({
        "path": path,
        "method": method,
        "description": description,
        "auth_required": auth_required,
    })
    return endpoints


# --------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------

def generate_report(endpoints: list) -> str:
    lines = []
    lines.append("# API Inventory Report")
    lines.append("")
    lines.append(f"_Generated by AutoVAPT API Mapper on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_")
    lines.append("")
    lines.append(f"Total endpoints discovered: **{len(endpoints)}**")
    lines.append("")
    lines.append("| # | Method | Path | Auth Required | Description |")
    lines.append("|---|--------|------|----------------|-------------|")
    for i, e in enumerate(endpoints, 1):
        lines.append(
            f"| {i} | {e.get('method', 'UNKNOWN')} | `{e['path']}` | "
            f"{e.get('auth_required', 'unknown')} | {e.get('description', '')} |"
        )
    lines.append("")
    lines.append("## Notes")
    lines.append("- This inventory is built incrementally during reconnaissance.")
    lines.append(
        "- Endpoints with `auth_required: unknown` should be checked for missing "
        "authentication / broken access control (OWASP API1 & API5)."
    )
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(description="AutoVAPT API Mapper")
    parser.add_argument("--db", default=str(DEFAULT_DB), help="Path to endpoints JSON database")
    parser.add_argument("--add", help="Add/update an endpoint path")
    parser.add_argument("--method", default="UNKNOWN", help="HTTP method for --add")
    parser.add_argument("--desc", default="", help="Description for --add")
    parser.add_argument("--auth", default="unknown", choices=["yes", "no", "unknown"],
                         help="Whether the endpoint requires auth")
    parser.add_argument("--list", action="store_true", help="List all stored endpoints")
    parser.add_argument("--report", help="Generate a Markdown report at this path")
    args = parser.parse_args(argv)

    db_path = Path(args.db)
    endpoints = load_endpoints(db_path)

    if args.add:
        endpoints = add_endpoint(endpoints, args.add, args.method.upper(), args.desc, args.auth)
        save_endpoints(db_path, endpoints)
        print(f"Stored: {args.method.upper()} {args.add}")

    if args.list or not (args.add or args.report):
        print(f"\n{len(endpoints)} endpoint(s) in {db_path}:")
        for e in endpoints:
            print(f"  [{e.get('method', 'UNKNOWN'):7}] {e['path']}  "
                  f"(auth: {e.get('auth_required', 'unknown')}) {e.get('description', '')}")

    if args.report:
        report = generate_report(endpoints)
        Path(args.report).parent.mkdir(parents=True, exist_ok=True)
        with open(args.report, "w") as fh:
            fh.write(report)
        print(f"\nReport written to {args.report}")


if __name__ == "__main__":
    main()
